// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <stdio.h>
#include <stdint.h>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_t.h"

// This is the function that the host calls. It prints
// a message in the enclave before calling back out to
// the host to print a message from there too.
double enclave_helloworld()
{
    fprintf(stdout, "Hello world from the enclave\n");

    double my_res = 0;
    volatile double my_num = 0.12345678899;

    asm("fldl %1\n\t"
        "fadd %%st, %%st\n\t"
        "fstl %0\n\t"
        : "=m"(my_res) : "m"(my_num) :
    );

    return my_res;
}
